# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  
  desc "Runs linting"
  lane :lint do
    gradle(task: "lint")
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Builds APK"
  lane :build_apk do
    gradle(task: "clean assembleDebug")
  end

  desc "Builds AAB"
  lane :build_aab do
    gradle(task: "clean bundleDebug")
  end

  desc "Uploads APK to Firebase App Distribution"
  lane :upload_to_firebase do |options|
    firebase_app_distribution(
      app: "1:607908723290:android:81e5b751b1515ce1407663",
      testers: "mrizqi070502@gmail.com",
      firebase_cli_token: "1//0gifWhp_5hJitCgYIARAAGBASNwF-L9IrswotIe8mKk5hJfVYsL0gblDvnafikoArQI5eBb9p-QyUfvmu4b9846UipLaXkxr2piA",
      android_artifact_type: "APK",
      android_artifact_path: "#{options[:workspace]}/app/build/outputs/apk/debug/app-debug.apk"
    )
  end
end

