name: Mahezza Android CI/CD for Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on:
      - ubuntu-latest

    steps:
    - name: Check out Git Repository
      uses: actions/checkout@v2

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Run lint
      run: ./gradlew lint

    - name: Upload html test report
      uses: actions/upload-artifact@v2
      with:
        name: lint-report
        path: app/build/reports/lint-results-debug.html
