name: Mahezza Android CI/CD for Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on:
      - ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Gradle clean
      run: ./gradlew clean

    - name: Run lint
      run: ./gradlew lint

    - name: Upload html test report
      uses: actions/upload-artifact@v2
      with:
        name: lint-report
        path: app/build/reports/lint-results-debug.html
